assembly_mappings:
  brake caliper: "Calipers"
  brake calipers: "Calipers"
  caliper: "Calipers"
  reservoire: "Brake Master Cylinder"
  reservoir: "Brake Master Cylinder"
  resovoir: "Brake Master Cylinder"
  fitting screw: "Fasteners"
  fastener: "Fasteners"
  screws: "Fasteners"
  bolts: "Fasteners"
  brake disc: "Brake Discs"
  brake disk: "Brake Discs"
  brake pad: "Brake Pads"
  brake line: "Brake Lines"
  master cylinder: "Brake Master Cylinder"
  damper: "Dampers"
  spring: "Springs"
  pushrod: "Pushrods"
  rocker: "Rockers"
  a-arm: "A-Arms"
  chain: "Chain"
  sprocket: "Sprockets"
  differential: "Differential"
  half shaft: "Half Shafts"
  halfshaft: "Half Shafts"
  steering rack: "Steering Rack"
  tie rod: "Tie Rods"
  steering wheel: "Steering Wheel"
  tire: "Tires"
  tyre: "Tires"
  wheel bearing: "Wheel Bearings"
  rim: "Wheels"
  wheel: "Wheels"
  rearwing: "Aerodynamics Rear Wing"
  frontwing: "Aerodynamics Front Wing"
  undertray: "Aerodynamics Underbody"
  body attachments: "Body Attachments"
  fronthoop: "Front Hoop"
  mainhoop: "Main Hoop"
  monocoque: "Monocoque"
  front end: "Front Part Frame"
  nose: "Impact Attenuator"

system_map:
  AT: "AT - Autonomous System"
  BR: "BR - Brake System"
  DT: "DT - Drivetrain"
  ET: "ET - Engine and Tractive System"
  FR: "FR - Chassis and Body"
  LV: "LV - Grounded Low Voltage System"
  MS: "MS - Miscellaneous Fit and Finish"
  ST: "ST - Steering System"
  SU: "SU - Suspension System"
  WT: "WT - Wheels, Wheel Bearings and Tires"

system_mappings:
  "C&B": "FR"
  "CB": "FR"
  "AS": "AT"
  "WH": "WT"
